steps:
  # 1. 建立 Docker 映像
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/hotel-web/web'
      - '-t'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/hotel-web/web:latest'
      - '.'

  # 2. 推送到 Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/$PROJECT_ID/hotel-web/web']

  # 3. 部署到 Cloud Run（不改變服務名稱，所以 URL 不會變）
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'hotel-web',
        '--image', 'asia-east1-docker.pkg.dev/$PROJECT_ID/hotel-web/web',
        '--platform', 'managed',
        '--region', 'asia-east1',
        '--allow-unauthenticated',
        '--service-account', 'forte-booking-system@forte-booking-system.iam.gserviceaccount.com',
        '--port', '8080',
        '--quiet'
      ]

images:
  - 'asia-east1-docker.pkg.dev/$PROJECT_ID/hotel-web/web'

